#!/bin/bash
#SBATCH -J SHP                               # 作业名为 test
#SBATCH -o SHP-%j.out                        # 屏幕上的输出文件重定向到 test.out
#SBATCH -p compute                            # 作业提交的分区为 compute
#SBATCH -N 1                                  # 作业申请 1 个节点
#SBATCH -t 144:00:00                           # 任务运行的最长时间为 1 小时
#SBATCH --mem 128g

# source ~/.bashrc

# 设置运行环境

# 输入要执行的命令，例如 ./hello 或 python test.py 等
python SHP.py                    # 执行命令